### ISSUE TITLE
Could not load background script 'vendor/xmlToJSON.js/lib/xmlToJSON.js'.

### ISSUE THREAD

**Issue by prabhakar267** [julmot/news-feed-for-github#3]
I tried loading the chrome extension from the source code but was facing this error
![screenshot from 2016-08-18 01-41-13](https://cloud.githubusercontent.com/assets/10768588/17751531/26fe0d14-64e5-11e6-91b8-7c8a71177179.png)

**Comment by julkue** [comment]
Hi @prabhakar267,

Could you please specify the steps to reproduce and the path you've chosen to import?

**Comment by julkue** [comment]
@prabhakar267 I know what you've done wrong.

Please read the [contribution guidelines](https://github.com/julmot/news-feed-for-github/blob/master/.github/CONTRIBUTING.md). It describes that you'll need to install vendor libraries first (`$ npm install` and `$ bower install`).
